config/routes.rb
Analytica::Application.routes.draw do

  root :to => 'products#hello'

  get 'products/hello' => 'products#hello'
  get 'products/goodbye' => 'products#goodbye'
  resources :products

end

app/models/product.rb
class Product
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :price, type: Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def hello
    @time = Time.now.strftime("%m/%d/%Y %I:%M%p")
    @files = Dir.glob('*')
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.slim
.navbar.navbar-default.navbar-static-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Analytica", root_path, class: "navbar-brand logo"

    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          a href="#about" Stories
        li
          a href="#contact" How It Works
        li
          a Start Your Project

      ul.nav.navbar-nav.navbar-right
        li
          a href="#" 
            | Welcome, 
            strong Gabriel
        li
          a href="#" Login
    /! /.nav-collapse

app/views/layouts/application.html.slim
doctype
  html
    head
      title Analytica
      = stylesheet_link_tag    "application"
      = stylesheet_link_tag    "application", "http://fonts.googleapis.com/css?family=Ubuntu:400,700"
      = stylesheet_link_tag    "application", "http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
      = javascript_include_tag "application"
      = csrf_meta_tags
    body
      / = render 'layouts/header'
      .pro-wrapper
        header.navbar-pro
          .navbar-toolbar
            .container
              .row
                .col-xs-3.left O
                .col-xs-6
                  .navbar-center
                    p.navbar-identity Analytica
                .col-xs-3.right >
        .pro-content
          .pro-content-hero
            .hero-message
              h1 Analytica makes simple social analytics easier
              h3 Get started with understanding your trends on Facebook, Twitter, etc
            .hero-info
              .container
                .row
                  .col.col-xs-8.col-xs-offset-2.col-md-4.col-md-offset-0
                    .hero-info-box
                      img alt="share" src="https://d1hjm33yswheja.cloudfront.net/img/icon-share.png" 
                      h4 Share links and notes
                      p Inc is a private place to share with your team, company or clients. You can share links, notes and files.
                  .col.col-xs-8.col-xs-offset-2.col-md-4.col-md-offset-0
                    .hero-info-box
                      img alt="share" src="https://d1hjm33yswheja.cloudfront.net/img/icon-share.png" 
                      h4 Share links and notes
                      p Inc is a private place to share with your team, company or clients. You can share links, notes and files.
                  .col.col-xs-8.col-xs-offset-2.col-md-4.col-md-offset-0
                    .hero-info-box
                      img alt="share" src="https://d1hjm33yswheja.cloudfront.net/img/icon-share.png" 
                      h4 Share links and notes
                      p Inc is a private place to share with your team, company or clients. You can share links, notes and files.


          .container
            .pro-content-header.text-center
              h1 Analytica makes simple social analytics easier
              h3 Get started with understanding your trends on Facebook, Twitter, etc
            br
            p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget tristique eros. Suspendisse iaculis non mauris ut tempus. Fusce ac varius felis. Donec feugiat commodo neque quis vehicula. Maecenas nec lobortis augue, at volutpat elit. Etiam posuere nisi id leo fringilla, at dictum erat pretium. Nunc aliquam viverra tincidunt. Vestibulum commodo eros luctus neque egestas, ut dictum felis venenatis.

            p Fusce ac tellus tincidunt, varius turpis vitae, blandit libero. Curabitur a aliquet magna. Fusce quis dui a augue ornare varius. Nullam at arcu sit amet sem faucibus luctus. Nullam ullamcorper sapien at est sodales molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In ultricies tortor ac arcu rhoncus gravida. Nunc dictum rhoncus lacus non placerat. Quisque cursus bibendum felis et mattis. Morbi ultrices tellus velit, eu vestibulum enim lobortis nec. Praesent eu sem non erat lacinia rhoncus. Phasellus id mattis massa, id auctor nisi. Duis lobortis commodo turpis, sed eleifend magna facilisis feugiat. Donec aliquet elit vitae porta iaculis.

            p Duis ut lectus dui. Nam fermentum est vel enim varius eleifend. Cras laoreet enim at malesuada rhoncus. Suspendisse potenti. Praesent ultrices dui in quam tempor adipiscing. Fusce a elit lectus. Maecenas et elementum sapien. Morbi eget orci lectus. Phasellus mollis sem in elementum luctus. In bibendum ut lacus in tincidunt. Aliquam erat volutpat. Pellentesque sit amet metus interdum, dapibus nunc ac, semper tellus. Suspendisse eu neque sapien. Nunc auctor adipiscing posuere. Cras nec neque purus.

            p Aliquam erat volutpat. Nulla quis lacinia mauris. In lobortis nisl at scelerisque dictum. Nulla rutrum egestas lorem a fringilla. Donec ac odio pellentesque, semper lacus in, lobortis elit. Nulla auctor massa nec aliquam euismod. Vivamus tempus venenatis adipiscing. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate pretium nisl, et porttitor mauris scelerisque nec. Ut leo purus, blandit eu tellus eget, fermentum molestie neque. Sed ut neque odio.

            p Donec mi orci, fringilla quis viverra ac, pharetra non tortor. Vivamus vitae turpis et nisl sollicitudin tincidunt. Integer molestie vulputate felis a pellentesque. Nulla ultrices aliquam sapien ac ultrices. Aenean viverra a nisl in aliquam. Ut rutrum tortor diam, a feugiat tortor scelerisque et. Sed interdum porttitor magna, congue hendrerit tortor eleifend eu. Integer faucibus arcu dictum, malesuada odio vitae, consectetur arcu. Vestibulum tempor vestibulum nisi, id dignissim risus posuere et. Nam eu dignissim est. Proin est nisl, cursus sed lectus vel, placerat aliquet justo. Aenean quis erat quis velit adipiscing venenatis vulputate vel libero. Maecenas hendrerit quis nunc nec pellentesque. Donec mollis metus vitae turpis dapibus, feugiat egestas purus interdum. Aliquam elit neque, congue vitae dui at, imperdiet commodo lacus. Morbi ut convallis lacus.

            p Fusce ac tellus tincidunt, varius turpis vitae, blandit libero. Curabitur a aliquet magna. Fusce quis dui a augue ornare varius. Nullam at arcu sit amet sem faucibus luctus. Nullam ullamcorper sapien at est sodales molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In ultricies tortor ac arcu rhoncus gravida. Nunc dictum rhoncus lacus non placerat. Quisque cursus bibendum felis et mattis. Morbi ultrices tellus velit, eu vestibulum enim lobortis nec. Praesent eu sem non erat lacinia rhoncus. Phasellus id mattis massa, id auctor nisi. Duis lobortis commodo turpis, sed eleifend magna facilisis feugiat. Donec aliquet elit vitae porta iaculis.

            p Duis ut lectus dui. Nam fermentum est vel enim varius eleifend. Cras laoreet enim at malesuada rhoncus. Suspendisse potenti. Praesent ultrices dui in quam tempor adipiscing. Fusce a elit lectus. Maecenas et elementum sapien. Morbi eget orci lectus. Phasellus mollis sem in elementum luctus. In bibendum ut lacus in tincidunt. Aliquam erat volutpat. Pellentesque sit amet metus interdum, dapibus nunc ac, semper tellus. Suspendisse eu neque sapien. Nunc auctor adipiscing posuere. Cras nec neque purus.

            p Aliquam erat volutpat. Nulla quis lacinia mauris. In lobortis nisl at scelerisque dictum. Nulla rutrum egestas lorem a fringilla. Donec ac odio pellentesque, semper lacus in, lobortis elit. Nulla auctor massa nec aliquam euismod. Vivamus tempus venenatis adipiscing. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate pretium nisl, et porttitor mauris scelerisque nec. Ut leo purus, blandit eu tellus eget, fermentum molestie neque. Sed ut neque odio.

            p Donec mi orci, fringilla quis viverra ac, pharetra non tortor. Vivamus vitae turpis et nisl sollicitudin tincidunt. Integer molestie vulputate felis a pellentesque. Nulla ultrices aliquam sapien ac ultrices. Aenean viverra a nisl in aliquam. Ut rutrum tortor diam, a feugiat tortor scelerisque et. Sed interdum porttitor magna, congue hendrerit tortor eleifend eu. Integer faucibus arcu dictum, malesuada odio vitae, consectetur arcu. Vestibulum tempor vestibulum nisi, id dignissim risus posuere et. Nam eu dignissim est. Proin est nisl, cursus sed lectus vel, placerat aliquet justo. Aenean quis erat quis velit adipiscing venenatis vulputate vel libero. Maecenas hendrerit quis nunc nec pellentesque. Donec mollis metus vitae turpis dapibus, feugiat egestas purus interdum. Aliquam elit neque, congue vitae dui at, imperdiet commodo lacus. Morbi ut convallis lacus.

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.text_field :price
  .actions = f.submit 'Save'

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/goodbye.html.slim
h1 Goodbye!

p It was nice having you here.
p
	= link_to "Go back in", products_hello_path

app/views/products/hello.html.slim
h1 Hello!

p 
	| It is now 
	= @time

p Glad to have you here.

strong Some cool files:

ul
	- @files.each do |file|
		li = file

p 
	| Time to say 
	= link_to "Goodbye", products_goodbye_path

app/views/products/index.html.slim
h1 Listing products

table
  tr
    th Name
    th Description
    th Price
    th
    th
    th

  - @products.each do |product|
    tr
      td = product.name
      td = product.description
      td = product.price
      td = link_to 'Show', product
      td = link_to 'Edit', edit_product_path(product)
      td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Description:
  = @product.description
p
  strong Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path